import type { Scenario } from "@/lib/story-format";

export const HA_AN_KHANH_SCENARIO: Scenario = {
  slug: "ha-an-khanh",
  title: "Hạ An & Khánh",
  tagline: "Cảm xúc hay lý trí",
  roleplay: {
    as: "Bạn vào vai Hạ An (học sinh cấp 3), giữa cảm xúc, ranh giới và áp lực.",
    summary:
      "Một hành trình nhập vai nhiều nhánh: từ tin nhắn người lạ, tình cảm tăng nhanh, đến những quyết định về ranh giới và sự an toàn.",
    mainCharacterId: "ha_an",
  },
  characters: [
    { id: "ha_an", name: "Hạ An", age: 17, bio: "Nhân vật chính, nhạy cảm nhưng biết tự quan sát bản thân." },
    { id: "khanh", name: "Nam Khánh", age: 19, bio: "Một người quen qua mạng, nói chuyện khéo và dẫn nhịp nhanh." },
    { id: "linh", name: "Linh", bio: "Bạn thân của Hạ An, quan sát tốt và thẳng tính." },
    { id: "mai", name: "Mai", bio: "Bạn cùng lớp, vui vẻ và tinh tế." },
    { id: "me", name: "Mẹ Hạ An", bio: "Mềm mỏng, luôn muốn con có chỗ dựa an toàn." },
  ],
  stats: [
    { id: "A", label: "Nhận thức", min: 0, max: 100 },
    { id: "E", label: "Cảm xúc", min: 0, max: 100 },
    { id: "T", label: "Tin tưởng", min: 0, max: 100 },
    { id: "P", label: "Áp lực", min: 0, max: 100 },
    { id: "B", label: "Ranh giới", min: 0, max: 100 },
  ],
  initialStats: { A: 30, E: 20, T: 20, P: 10, B: 30 },
  flags: [
    { id: "red", label: "RedFlag", tone: "bad" },
    { id: "green", label: "GreenFlag", tone: "good" },
  ],
  initialFlags: { red: 0, green: 0 },
  routes: [],
  startNodeId: "scene1",
  nodes: {
    scene1: {
      id: "scene1",
      kind: "scene",
      title: "SCENE 1 – ĐÊM TĨNH LẶNG",
      body: [],
      lines: [
        { text: "Phòng tối. Ánh sáng điện thoại hắt lên gương mặt Hạ An." },
        { text: "Một thông báo xuất hiện: “Nam Khánh đã gửi lời mời kết bạn.”" },
        { speakerId: "khanh", text: "Hello em, anh thấy em học trường cũ của anh nên muốn làm quen ^^" },
        { speakerId: "ha_an", text: "(Người lạ... nhưng cũng chưa có gì đáng nghi rõ ràng.)" },
      ],
      choices: [
        {
          id: "s1_a",
          label: "Trả lời thân thiện",
          next: "scene2a",
          effect: { stats: { E: 15, T: 10, B: -5, P: 5 } },
          resultLine: { speakerId: "ha_an", text: "Dạ em chào anh, anh cũng từng học trường em ạ?" },
        },
        {
          id: "s1_b",
          label: "Trả lời lịch sự",
          next: "scene2b",
          effect: { stats: { A: 15, B: 10 } },
          resultLine: { speakerId: "ha_an", text: "Dạ, em cảm ơn anh. Mình nói chuyện bình thường thôi nha." },
        },
        {
          id: "s1_c",
          label: "Bỏ qua",
          next: "end_safe_1",
          effect: { stats: { B: 15, T: -10 } },
          resultLine: { speakerId: "ha_an", text: "(Mình không nợ ai một lời hồi đáp khi chưa thấy an toàn.)" },
        },
      ],
    },
    scene2a: {
      id: "scene2a",
      kind: "scene",
      title: "SCENE 2A – NHỮNG TIN NHẮN ĐẦU TIÊN",
      body: [],
      lines: [
        { text: "Tin nhắn bắt đầu xuất hiện mỗi ngày." },
        { speakerId: "khanh", text: "Em học lớp nào? Trường đó giờ thay đổi nhiều không?" },
        { text: "Ban đầu Hạ An trả lời như một cuộc trò chuyện xã giao, không để tâm quá nhiều." },
        { text: "Nhưng dần dần, nhịp tin nhắn đổi khác: sáng chúc ngày tốt lành, tối nhắc ngủ sớm." },
        { speakerId: "ha_an", text: "(Một thói quen đang hình thành lúc nào không biết.)" },
      ],
      choices: [
        {
          id: "s2a_a",
          label: "Trả lời nhanh và nhiệt tình",
          next: "scene2a_1",
          effect: { stats: { E: 10, T: 10, B: -5 } },
          resultLine: { speakerId: "khanh", text: "Nói chuyện với em lúc nào cũng thấy vui." },
        },
        {
          id: "s2a_b",
          label: "Trả lời khi rảnh",
          next: "scene2a_1",
          effect: { stats: { A: 10, B: 5 } },
          resultLine: { speakerId: "ha_an", text: "Em rep hơi chậm nha, tại còn phải học nữa." },
        },
      ],
    },
    scene2a_1: {
      id: "scene2a_1",
      kind: "scene",
      title: "SCENE 2A_1 – SỰ QUAN TÂM TĂNG DẦN",
      body: [],
      lines: [
        { text: "Một tối, Hạ An đăng story: “Học mệt quá...”." },
        { speakerId: "khanh", text: "Đừng cố quá, giữ sức nha." },
        { text: "Phản hồi đến gần như ngay lập tức làm Hạ An bất ngờ." },
        { text: "Từ đó, những cuộc trò chuyện bắt đầu dài hơn: gia đình, bạn bè, áp lực học tập." },
        { speakerId: "ha_an", text: "(Mình đang kể nhiều hơn dự định ban đầu.)" },
      ],
      choices: [
        {
          id: "s2a1_a",
          label: "Chia sẻ chuyện cá nhân sâu hơn",
          next: "scene2a_2",
          effect: { stats: { E: 15, A: -5, B: -5, T: 10 } },
          resultLine: { speakerId: "khanh", text: "Cảm ơn em vì đã tin anh như vậy." },
        },
        {
          id: "s2a1_b",
          label: "Giữ ở mức bình thường",
          next: "scene2a_2",
          effect: { stats: { A: 10, B: 10 } },
          resultLine: { speakerId: "ha_an", text: "(Mình có thể mở lòng, nhưng vẫn cần giữ phần riêng của mình.)" },
        },
      ],
    },
    scene2a_2: {
      id: "scene2a_2",
      kind: "scene",
      title: "SCENE 2A_2 – THÓI QUEN NGUY HIỂM",
      body: [],
      lines: [
        { text: "Một ngày không có tin nhắn." },
        { text: "Hạ An mở điện thoại, rồi tắt, rồi lại mở." },
        { speakerId: "ha_an", text: "(Tại sao hôm nay không nhắn?)" },
        { text: "Đến tối, Khánh mới nhắn: “Xin lỗi em, hôm nay anh bận.”" },
        { text: "Hạ An thấy nhẹ nhõm một cách kỳ lạ." },
      ],
      choices: [
        {
          id: "s2a2_a",
          label: "Nhận ra mình đang phụ thuộc",
          next: "scene3",
          effect: { stats: { A: 15, B: 10 } },
          resultLine: { speakerId: "ha_an", text: "(Nếu không dừng lại nhìn, mình sẽ bị thói quen này kéo đi.)" },
        },
        {
          id: "s2a2_b",
          label: "Bỏ qua cảm giác đó",
          next: "scene3",
          effect: { stats: { E: 10, P: 5 } },
          resultLine: { speakerId: "ha_an", text: "(Chắc do mình nghĩ nhiều thôi.)" },
        },
      ],
    },
    scene2b: {
      id: "scene2b",
      kind: "scene",
      title: "SCENE 2B – GIỮ NHỊP",
      body: [],
      lines: [
        { text: "Cuộc trò chuyện không quá sâu. Hạ An vẫn kiểm soát nhịp của mình." },
        { speakerId: "ha_an", text: "(Mình thấy dễ thở hơn khi không để mọi thứ đi quá nhanh.)" },
      ],
      choices: [{ id: "s2b_n", label: "Tiếp tục", next: "scene3" }],
    },
    scene3: {
      id: "scene3",
      kind: "scene",
      title: "SCENE 3 – LẦN ĐẦU GỌI ĐIỆN",
      body: [],
      lines: [
        { speakerId: "khanh", text: "Hay mình gọi điện thử không?" },
        { text: "Hạ An do dự một chút, rồi vẫn đồng ý." },
        { text: "Cuộc gọi kéo dài hơn 1 tiếng. Ban đầu ngượng, sau đó lại thành tự nhiên." },
        { text: "Tiếng cười xen những khoảng lặng, để lại một cảm giác khó gọi tên." },
        { speakerId: "ha_an", text: "(Kết thúc cuộc gọi rồi mà mình vẫn chưa ngủ được.)" },
      ],
      choices: [
        {
          id: "s3_a",
          label: "Chủ động nhắn lại sau cuộc gọi",
          next: "scene4_pre",
          effect: { stats: { E: 10, T: 10 } },
          resultLine: { speakerId: "khanh", text: "Nghe giọng em, anh thấy cả ngày nhẹ hẳn." },
        },
        {
          id: "s3_b",
          label: "Đợi đối phương nhắn",
          next: "scene4_pre",
          effect: { stats: { A: 10 } },
          resultLine: { speakerId: "ha_an", text: "(Mình muốn bình tĩnh hơn, đừng để cảm xúc kéo đi quá nhanh.)" },
        },
      ],
    },
    scene4_pre: {
      id: "scene4_pre",
      kind: "scene",
      title: "SCENE 4_PRE – NHỮNG TÍN HIỆU MƠ HỒ",
      body: [],
      lines: [
        { text: "Khánh bắt đầu nhắn thường xuyên hơn, gọi Hạ An là “bé”, quan tâm nhiều hơn mức bình thường." },
        { speakerId: "ha_an", text: "(Đây có phải là thích không?)" },
        { text: "Nhưng cả hai vẫn chưa ai nói rõ." },
        { speakerId: "khanh", text: "Anh thấy nói chuyện với em... khác với người khác." },
        { text: "Tim Hạ An chững lại trong vài giây." },
      ],
      choices: [
        {
          id: "s4pre_a",
          label: "Đáp lại một cách tình cảm",
          next: "scene4",
          effect: { stats: { E: 15, B: -5 } },
          resultLine: { speakerId: "ha_an", text: "Nói chuyện với anh em cũng thấy đặc biệt." },
        },
        {
          id: "s4pre_b",
          label: "Giữ khoảng cách",
          next: "scene4",
          effect: { stats: { A: 10, B: 10 } },
          resultLine: { speakerId: "ha_an", text: "Em quý anh, nhưng em muốn mọi thứ rõ ràng và chậm lại." },
        },
      ],
    },
    scene4: {
      id: "scene4",
      kind: "scene",
      title: "SCENE 4 – LINH NHẬN RA",
      body: [],
      lines: [
        { speakerId: "linh", text: "Mày dạo này cười nhiều hơn đấy." },
        { speakerId: "linh", text: "Mà... có phải đang nói chuyện với ai không?" },
        { text: "Hạ An im lặng một chút. Câu trả lời nằm ngay ở cổ họng." },
      ],
      choices: [
        {
          id: "s4_a",
          label: "Kể cho Linh nghe",
          next: "scene5_pre",
          effect: { stats: { A: 15, B: 10, P: -10 } },
          resultLine: { speakerId: "linh", text: "Tao không phán xét. Tao chỉ muốn mày không bị cuốn mù luôn." },
        },
        {
          id: "s4_b",
          label: "Né tránh",
          next: "scene5_pre",
          effect: { stats: { E: 10, P: 10 } },
          resultLine: { speakerId: "ha_an", text: "Không có gì đâu, tao chỉ hơi mệt thôi." },
        },
      ],
    },
    scene5_pre: {
      id: "scene5_pre",
      kind: "scene",
      title: "SCENE 5_PRE – CĂNG THẲNG TRƯỚC LỜI TỎ TÌNH",
      body: [],
      lines: [
        { text: "Tối đó, tin nhắn đến muộn hơn bình thường." },
        { speakerId: "khanh", text: "Anh có chuyện muốn nói..." },
        { text: "Hạ An đọc đi đọc lại mà không dám mở tiếp." },
        { speakerId: "ha_an", text: "(Tim đập nhanh. Mình biết có gì đó sắp thay đổi.)" },
      ],
      choices: [{ id: "s5pre_n", label: "Tiếp tục", next: "scene5" }],
    },
    scene4_safe: {
      id: "scene4_safe",
      kind: "scene",
      title: "SCENE 4_SAFE – TỈNH TÁO CAO",
      body: [],
      lines: [
        { text: "Nhờ có Linh, Hạ An bắt đầu nhìn lại ranh giới của mình rõ hơn." },
        { speakerId: "ha_an", text: "(Mình có quyền thích một người, và cũng có quyền chậm lại.)" },
      ],
      choices: [{ id: "s4s_n", label: "Tiếp tục", next: "scene5" }],
    },
    scene4_risk: {
      id: "scene4_risk",
      kind: "scene",
      title: "SCENE 4_RISK – CUỐN THEO CẢM XÚC",
      body: [],
      lines: [
        { text: "Hạ An dần lệ thuộc vào tin nhắn. Không rep là thấy khó chịu." },
        { speakerId: "mai", text: "Mày ổn chứ? Mặt mày căng quá." },
      ],
      choices: [{ id: "s4r_n", label: "Tiếp tục", next: "scene5" }],
    },
    scene5: {
      id: "scene5",
      kind: "scene",
      title: "SCENE 5 – LỜI TỎ TÌNH",
      body: [],
      lines: [
        { speakerId: "khanh", text: "Anh thích em." },
        { text: "Không phải đột ngột nữa. Mọi thứ trước đó đã dẫn đến khoảnh khắc này." },
        { speakerId: "ha_an", text: "(Nhưng khi nó xảy ra thật, mình vẫn chưa sẵn sàng hoàn toàn.)" },
      ],
      choices: [
        {
          id: "s5_a",
          label: "Đồng ý",
          next: "scene6",
          effect: { stats: { E: 25, T: 20, B: -10 } },
          resultLine: { speakerId: "khanh", text: "Từ giờ có gì cũng kể anh đầu tiên nha." },
        },
        {
          id: "s5_b",
          label: "Cần thời gian",
          next: "scene6",
          effect: { stats: { A: 15, B: 10 } },
          resultLine: { speakerId: "ha_an", text: "Em trân trọng anh, nhưng em muốn chậm lại để chắc chắn." },
        },
        {
          id: "s5_c",
          label: "Từ chối",
          next: "end_safe_2",
          effect: { stats: { A: 20 } },
          resultLine: { speakerId: "ha_an", text: "Em không muốn bắt đầu khi em chưa thật sự sẵn sàng." },
        },
      ],
    },
    scene6: {
      id: "scene6",
      kind: "scene",
      title: "SCENE 6 – 4 THÁNG SAU",
      body: [],
      lines: [
        { text: "Quan hệ tiến triển: gọi điện mỗi tối, đi chơi riêng, tin tưởng tăng nhanh." },
        { text: "Nhưng Hạ An bắt đầu chia sẻ gần như mọi thứ và ít giữ lại không gian cho bản thân." },
      ],
      choices: [
        {
          id: "s6_a",
          label: "Sống theo cảm xúc",
          next: "toxic_check",
          effect: { stats: { E: 25, A: -15, B: -15, P: 15 } },
          resultLine: { speakerId: "ha_an", text: "(Mình đang làm mọi thứ để giữ mối quan hệ này.)" },
        },
        {
          id: "s6_b",
          label: "Giữ cân bằng",
          next: "route_healthy",
          effect: { stats: { A: 20, B: 10 } },
          resultLine: { speakerId: "ha_an", text: "Em vẫn quý anh, nhưng em cần thời gian cho học tập và bạn bè." },
        },
        {
          id: "s6_c",
          label: "Nhận ra và dừng",
          next: "end_safe_3",
          effect: { stats: { A: 25, B: 20 } },
          resultLine: { speakerId: "linh", text: "Quyết định khó, nhưng mày vừa tự cứu mình đó." },
        },
      ],
    },
    toxic_check: {
      id: "toxic_check",
      kind: "scene",
      title: "ROUTE TOXIC_CHECK",
      body: [],
      lines: [{ text: "Hạ An thử nhìn lại mối quan hệ qua các dấu hiệu thực tế." }],
      choices: [
        { id: "tc_toxic", label: "Tiếp tục", next: "route_toxic", requires: { all: [{ stat: { key: "E", op: ">=", value: 60 } }, { stat: { key: "B", op: "<=", value: 20 } }] } },
        { id: "tc_normal", label: "Tiếp tục", next: "scene7", requires: { not: { all: [{ stat: { key: "E", op: ">=", value: 60 } }, { stat: { key: "B", op: "<=", value: 20 } }] } } },
      ],
    },
    route_toxic: {
      id: "route_toxic",
      kind: "scene",
      title: "ROUTE TOXIC – NGƯỜI YÊU KIỂM SOÁT",
      body: [],
      lines: [
        { speakerId: "khanh", text: "Sao em rep chậm? Em đang nói chuyện với ai?" },
        { text: "Hạ An thấy khó chịu nhưng không dám phản kháng mạnh." },
      ],
      choices: [{ id: "rt_n", label: "Tiếp tục", next: "scene7" }],
    },
    route_healthy: {
      id: "route_healthy",
      kind: "scene",
      title: "ROUTE HEALTHY – MỐI QUAN HỆ ỔN ĐỊNH",
      body: [],
      lines: [
        { text: "Hai bạn vẫn vui vẻ. Hạ An giữ không gian riêng và không chia sẻ mọi thứ." },
        { speakerId: "khanh", text: "Ừ, anh tôn trọng lịch của em." },
      ],
      choices: [{ id: "rh_n", label: "Tiếp tục", next: "scene7" }],
    },
    scene7: {
      id: "scene7",
      kind: "scene",
      title: "SCENE 7 – KHÔNG GIAN RIÊNG",
      body: [],
      lines: [
        { speakerId: "khanh", text: "Anh nghĩ chúng mình đủ hiểu nhau rồi..." },
        { speakerId: "ha_an", text: "(Mình hiểu ý. Tim đập nhanh, đầu óc thì rối.)" },
      ],
      choices: [
        {
          id: "s7_a",
          label: "Đồng ý",
          next: "scene8",
          effect: { stats: { E: 30, B: -20, P: 20 } },
          resultLine: { speakerId: "ha_an", text: "(Mình đồng ý, nhưng lòng mình chưa thật sự yên.)" },
        },
        {
          id: "s7_b",
          label: "Từ chối",
          next: "respect_check",
          effect: { stats: { B: 25, A: 20 } },
          resultLine: { speakerId: "ha_an", text: "Em chưa sẵn sàng. Em muốn anh tôn trọng điều đó." },
        },
      ],
    },
    respect_check: {
      id: "respect_check",
      kind: "scene",
      title: "ROUTE RESPECT_CHECK",
      body: [],
      lines: [{ text: "Phản ứng của Khánh sẽ cho thấy đây là tôn trọng hay gây áp lực." }],
      choices: [
        {
          id: "rc_good",
          label: "Tiếp tục",
          next: "end_good_respect",
          requires: { stat: { key: "T", op: ">=", value: 50 } },
        },
        {
          id: "rc_bad",
          label: "Tiếp tục",
          next: "end_bad_break",
          requires: { stat: { key: "T", op: "<", value: 50 } },
        },
      ],
    },
    scene8: {
      id: "scene8",
      kind: "scene",
      title: "SCENE 8 – HẬU QUẢ",
      body: [],
      lines: [
        { text: "Vài tuần sau, cơ thể thay đổi. Hạ An lo lắng và mất ngủ." },
        { speakerId: "ha_an", text: "Mình phải làm gì...?" },
      ],
      choices: [
        {
          id: "s8_a",
          label: "Giữ kín",
          next: "end_bad_silent",
          effect: { stats: { P: 30, A: -15 } },
          resultLine: { speakerId: "ha_an", text: "(Mình sẽ tự chịu được... chắc vậy.)" },
        },
        {
          id: "s8_b",
          label: "Tự tìm hiểu",
          next: "end_mid_alone",
          effect: { stats: { A: 20 } },
          resultLine: { speakerId: "linh", text: "Tìm hiểu là tốt, nhưng mày vẫn cần người đồng hành." },
        },
        {
          id: "s8_c",
          label: "Nói với bố mẹ",
          next: "end_good_family",
          effect: { stats: { A: 15, T: 20, B: 10 } },
          resultLine: { speakerId: "me", text: "Mẹ ở đây. Mình cùng xử lý từng bước, không để con một mình." },
        },
      ],
    },
    end_safe_1: {
      id: "end_safe_1",
      kind: "ending",
      title: "END SAFE_1 – KHÔNG BẮT ĐẦU",
      body: ["Bạn chọn an toàn tuyệt đối. Không có rủi ro."],
      choices: [{ id: "r1", label: "Chơi lại", next: "scene1" }],
    },
    end_safe_2: {
      id: "end_safe_2",
      kind: "ending",
      title: "END SAFE_2 – TỪ CHỐI SỚM",
      body: ["Bạn hiểu bản thân và không bị cuốn theo cảm xúc."],
      choices: [{ id: "r2", label: "Chơi lại", next: "scene1" }],
    },
    end_safe_3: {
      id: "end_safe_3",
      kind: "ending",
      title: "END SAFE_3 – DỪNG ĐÚNG LÚC",
      body: ["Bạn nhận ra sớm và dừng lại. Đây là dấu hiệu của trưởng thành."],
      choices: [{ id: "r3", label: "Chơi lại", next: "scene1" }],
    },
    end_good_respect: {
      id: "end_good_respect",
      kind: "ending",
      title: "END GOOD_RESPECT – TÌNH YÊU LÀNH MẠNH",
      body: [
        "Người yêu tôn trọng bạn, không ép buộc.",
        "Bạn giữ được ranh giới và cảm xúc không còn lấn át lý trí.",
      ],
      choices: [{ id: "r4", label: "Chơi lại", next: "scene1" }],
    },
    end_bad_break: {
      id: "end_bad_break",
      kind: "ending",
      title: "END BAD_BREAK – MỐI QUAN HỆ ĐỔ VỠ",
      body: [
        "Bạn bị trách móc: “Em không yêu anh thật lòng.”",
        "Bạn nhận ra đó không phải tình yêu lành mạnh.",
      ],
      choices: [{ id: "r5", label: "Chơi lại", next: "scene1" }],
    },
    end_bad_silent: {
      id: "end_bad_silent",
      kind: "ending",
      title: "END BAD_SILENT – IM LẶNG",
      body: ["Bạn chịu đựng một mình. Áp lực tăng dần và mọi thứ vỡ ra muộn."],
      choices: [{ id: "r6", label: "Chơi lại", next: "scene1" }],
    },
    end_mid_alone: {
      id: "end_mid_alone",
      kind: "ending",
      title: "END MID_ALONE – HIỂU NHƯNG CÔ ĐƠN",
      body: ["Bạn có kiến thức nhưng thiếu hỗ trợ nên vẫn rất đơn độc."],
      choices: [{ id: "r7", label: "Chơi lại", next: "scene1" }],
    },
    end_good_family: {
      id: "end_good_family",
      kind: "ending",
      title: "END GOOD_FAMILY – KHÔNG CÒN MỘT MÌNH",
      body: [
        "Bạn nói với bố mẹ. Ban đầu rất sợ, nhưng họ không quay lưng.",
        "Bạn được hỗ trợ để giải quyết từng bước và hiểu rằng gia đình là nơi an toàn.",
        "Thông điệp: cảm xúc không sai, nhưng cần lý trí dẫn đường; ranh giới là thứ bạn phải tự giữ.",
      ],
      choices: [{ id: "r8", label: "Chơi lại", next: "scene1" }],
    },
  },
};

